# Generated by Django 3.2 on 2021-06-05 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Endorsement',
        ),
    ]
